### ISSUE TITLE
Add support for managing an OpenShift route object and pointing it at the istio gateway with a related VirtualService

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#103]

**Comment by maleck13** [comment]
should the virtual service be created in a protected namespace

**Comment by maleck13** [comment]
As part of this work we should also put together a complex route with paths and multiple backends

**Comment by eguzki** [comment]
We may have an issue with the following sentence `update the Route object to point at the Istio Gateway` from the spec in #102 

The route target `to` field can make reference to services _only_ in the same namespace as the route object. https://docs.openshift.com/container-platform/4.9/rest_api/network_apis/route-route-openshift-io-v1.html. Same for the [ingress object](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingressservicebackend-v1-networking-k8s-io). Whereas for the ingress resource this is not an issue, for the Openshift Route resource it is an issue.

Istio ingress gateway can be the cluster's ingress gateway. So the customer creates the ingress in the same namespace of the owned API service and kuadrant can apply authZ and RateLimit capabilities at the Istio ingress gateway.

For the openshift routes case, the cluster ingress gateway is the HAProxy provided by OCP. The istio ingress gateway, where kuadrant can apply authZ and rate limit capabilities, is usually in located at a protected namespace. So, unless the customer deploys custom istio gateways in his own namespace, the customer's route object cannot have the istio gateway service as target. 

I wonder if the only alternative here is that the customer needs to deploy his own Istio gateway at his own namespace and add the gateway's service reference as annotation in the route. But that makes kuadrant integration less seamless with his route object.

cc @maleck13

**Comment by maleck13** [comment]
Ah yes. Hmm that is a bit of blocker. Makes sense that a route would point to a service in it's own namespace. I guess this is why 3scale generates the routes in the APICast ns.   I guess we could look to leverage the sidecar model for Routes. The only other option it would seem would be to allow the route to be created in the gateway ns. Neither of which are ideal.

**Comment by maleck13** [comment]
I guess OSSM must generate the route in the same ns as the gateway object also

**Comment by eguzki** [comment]
The sidecar model seems more intrusive in the API owner deployment. I can follow up the headless service option. It is kind of a hack, which I do not know how it would work if the route does not end TLS connection, but I guess it might work.

**Comment by maleck13** [comment]
yeah with the TLS thing, I am not sure if the service is going to make a difference there? Unless I am mis understanding something. But I guess it something we will have to test

**Comment by eguzki** [comment]
I am afraid, the headless service with reference to the kuadrant gateway service is not feasible. At least, I could not manage to make it work. 

My guess, I can only guess because I could not find OCP 4.X doc about this issue, is that the ingress gateway (the HAProxy) does load balancing instead of the service it points to. In order to do that, the HAProxy is configured with **endpoints**, which are IP:PORT based data structs that belong to services (which are not headless). The [doc from OCP 3.11](https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html) explains way better than me:
```
A router uses the service selector to find the service and the endpoints backing the service. 
When both router and service provide load balancing, OpenShift Container Platform uses the router load balancing. 
A router detects relevant changes in the IP addresses of its services and adapts its configuration accordingly. 
This is useful for custom routers to communicate modifications of API objects to an external routing solution.
```

When I create a route with reference to a service that does load balancing (clusterIP type), the route metadata shows the endpoints backing the service

```
❯ oc describe route toystore
Name:		toystore
Namespace:	eguzki
Created:	3 hours ago
...
Path:			<none>
TLS Termination:	<none>
Insecure Policy:	<none>
Endpoint Port:		3000

Service:	toystore
Weight:		100 (100%)
Endpoints:	10.129.1.184:3000
```

When I create a route with reference to a headless service, the route metadata shows an error because there are no endpoints.

The headless service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: eguzki-test
spec:
  externalName: toystore.eguzki.svc.cluster.local
  type: ExternalName
status:
  loadBalancer: {}
```
The route with reference to the headless service
```
oc describe route toystore 
Name:		toystore
Namespace:	eguzki
....
Path:			<none>
TLS Termination:	<none>
Insecure Policy:	<none>
Endpoint Port:		3000

Service:	eguzki-test
Weight:		100 (100%)
Endpoints:	<error: endpoints "eguzki-test" not found>
```

The route pointing to the clusterIP service exposes the service externally, whereas the route pointing to the headless service does not. 

Note that I did not even try referencing a service from ANOTHER namespace. 

Interesting to note, that somehow confirms this theory of the HAProxy being configured with endpoints as backends instead of service (DNS) names is the route's `spec.port.targetPort` value needs to be the pods port, not the port of the service. The service allows port mapping, so the route's needs to be configured with the service's `targetPort` instead of the `port`. This makes sense if HAProxy works with pod endpoints instead of the port exposed from the service.  One example to illusttrate this:

Having this service:

```yaml
apiVersion: v1
kind: Service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: toystore
  type: ClusterIP
```

The route needs to be configured with the port 3000. If, instead, the route is configured with the port 80, the API will not be exposed. Using the name is very convenient as the route controller configures HAProxy accordingly with the `targetPort` and you do not even know about it.

**Comment by maleck13** [comment]
hmm ok. So perhaps we need to look more closely at what OSSM does with routes. Is the route created in the same namespace as the gateway for example? It would seem this is the only option (IE we either have a side car or we move the route to the same namespace as the ingress gateway)

**Comment by maleck13** [comment]
thinking about this further, sidecar could be a good option for a standalone cluster, but when integrating with KCP we look at translating from route to VirtualService/Gateway api object at the KCP layer.
